# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jen Haskell
tagline:          
url:              http://jchaskell.github.io
paginate:         1
baseurl:          /
author:
  name:           Jen Haskell
  url:            https://jchaskell.github.io
  email:          jhaskell@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jchaskell
